# Module: plugin.video.simonscat
# Author: Deny Kubisz
# Created on: 12.12.2018
# License: GPL v.3 https://www.gnu.org/copyleft/gpl.html

import sys
from urllib import urlencode
from urlparse import parse_qsl
import xbmcgui
import xbmcplugin

_url = sys.argv[0]
_handle = int(sys.argv[1])

VIDEOS = {'SIMON’S CAT Collection': [
                      {'name': 'SIMON’S CAT – TOP 10 EPISODE COUNTDOWN',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/sHWEc-yxfb4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/sHWEc-yxfb4',
                       'genre': 'Collections'},
                      {'name': 'PAWS & CHORES – SIMON’S CAT / STORYTIME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/UL9LnPa-3A4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/UL9LnPa-3A4',
                       'genre': 'Collections'},
                      {'name': 'THE MAKING OF – SIMON’S CAT / OFF TO THE VET',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/XJ5J1BPA8IQ&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/XJ5J1BPA8IQ',
                       'genre': 'Collections'},
                      {'name': 'TINY TERROR – SIMON’S CAT COLLECTION',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/nvR5ZNegmxE&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/nvR5ZNegmxE',
                       'genre': 'Collections'},
                      {'name': 'SIMON’S CAT – THANK YOU COLLECTION',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/dVEuiQK553w&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/dVEuiQK553w',
                       'genre': 'Collections'},
                      {'name': 'SIMON’S CAT – GARDEN COLLECTION',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/BMNwrrFTO7A&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/BMNwrrFTO7A',
                       'genre': 'Collections'},     
                      {'name': 'SIMON’S CAT & FRIENDS – COLLECTION',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/XrOjPPUI5T0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/XrOjPPUI5T0',
                       'genre': 'Collections'},                   
                      ],
            'SIMON’S CAT Sketches': [
                      {'name': 'SIMON’S CAT SKETCHES – PRIMAL INSTINCT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/-sFc6pscbYk&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/-sFc6pscbYk',
                       'genre': 'Sketches'},  
                      {'name': 'SIMON’S CAT SKETCHES – UFO',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/pFy3jZk1Tko&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/pFy3jZk1Tko',
                       'genre': 'Sketches'},  
                     ],
            'SIMON’S CAT Logic': [
                      {'name': 'SIMON’S CAT LOGIC – CATS ON THE MOVE!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/VyjwNFZti8A&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/VyjwNFZti8A',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – WHEN YOUR CAT GOES MISSING!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/iLJrG0hDI-8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/iLJrG0hDI-8',
                       'genre': 'Logic'},  
                      {'name': 'WHY EVERYONE SHOULD HAVE A CAT! FT. ANNA AKANA – SIMON’S CAT | COLLAB',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/xm8dNxs8fiQ&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/xm8dNxs8fiQ',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – TERRITORIAL BEHAVIOUR',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/r-7-bIXETfY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/r-7-bIXETfY',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – WHY DO CATS GO CRAZY FOR CATNIP?',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/vKHeHQ1QRqo&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/vKHeHQ1QRqo',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – WHAT DO CATS WANT FOR CHRISTMAS?',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/aliDVYH08pg&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/aliDVYH08pg',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – ARE BLACK CATS UNLUCKY?',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/WVOVKHQ0N4I&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/WVOVKHQ0N4I',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – HOW CAN I ENTERTAIN MY CAT?',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/BY3SLVNBkeo&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/BY3SLVNBkeo',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT CARE – HOW TO CARE FOR KITTENS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/-1fzGnFwz9M&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/-1fzGnFwz9M',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – WHY DO CATS LIKE HUNTING?',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/MWUjME5UEBw&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/MWUjME5UEBw',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC: 1-3 COLLECTION!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/xG5e65CGljI&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/xG5e65CGljI',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – THINGS YOU DIDN’T KNOW ABOUT RAGDOLLS!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/IDgP9BJSd2A&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/IDgP9BJSd2A',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – THINGS YOU DIDN’T KNOW ABOUT FEEDING TIME!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/g4dDZgBfHBk&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/g4dDZgBfHBk',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – HOW DO CATS STAY SO CLEAN?',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/5hVkPiWx4R8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/5hVkPiWx4R8',
                       'genre': 'Logic'},  
                      {'name': 'SIMON’S CAT LOGIC – WHY DO CATS SLEEP IN UNUSUAL PLACES?!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/lqT-hmTiL4Y&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/lqT-hmTiL4Y',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – WHY DO CATS LOVE BOXES?!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/KDDM_XGNj2c&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/KDDM_XGNj2c',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – LET ME IN, LET ME OUT!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/wmCJeEd3_4w&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/wmCJeEd3_4w',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – LOVE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/SUktj3SB6zY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/SUktj3SB6zY',
                       'genre': 'Logic'}, 
                      {'name': 'SIMON’S CAT LOGIC – CRAZY TIME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/lisncxkbHfc&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/lisncxkbHfc',
                       'genre': 'Logic'}, 
                     ],
            'SIMON’S CAT Guide To': [
                      {'name': 'SIMON’S CAT – A GUIDE TO FRIENDS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/jQXrci8h684&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/jQXrci8h684',
                       'genre': 'Guide To'},  
                      {'name': 'SIMON’S CAT – A GUIDE TO SPRING SEASON',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/hu3tAjLaBWw&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/hu3tAjLaBWw',
                       'genre': 'Guide To'},  
                      {'name': 'SIMON’S CAT – CATS VS BOXES (PART 3)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/cDjYY7nW7cY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/cDjYY7nW7cY',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – A GUIDE TO EATING HABITS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/uYaN4OLxm08&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/uYaN4OLxm08',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – A GUIDE TO NEW YEAR RESOLUTIONS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/KNEVjhCXZB4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/KNEVjhCXZB4',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – A GUIDE TO HUMANS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/vW4rpQ-rfHA&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/vW4rpQ-rfHA',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – A GUIDE TO BIRTHDAYS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/qEEtzzi1EII&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/qEEtzzi1EII',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – A GUIDE TO CAT YOGA',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/q99rhZlYlAo&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/q99rhZlYlAo',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – CAT VS BOXES (PART 2)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/OXzugTmRQpM&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/OXzugTmRQpM',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – CAT VS BOXES (PART 1)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/1mLxxxOMcs8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/1mLxxxOMcs8',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – CAMOUFLAGE CHALLENGE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/K9GTvCc0PnM&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/K9GTvCc0PnM',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT – A GUIDE TO A CAT’S LOVE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/ma4L3hL9TNU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/ma4L3hL9TNU',
                       'genre': 'Guide To'}, 
                      {'name': 'A CHRISTMAS CHECKLIST',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/MAJ0zgJd4p0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/MAJ0zgJd4p0',
                       'genre': 'Guide To'}, 
                      {'name': 'SIMON’S CAT GUIDE TO WINTER!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/0FFl3UCX3vY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/0FFl3UCX3vY',
                       'genre': 'Guide To'}, 
                     ],
            'SIMON’S CAT Snaps': [
                      {'name': 'JUST LIKE MY CAT EPISODE 1 – SIMON’S CAT SNAPS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/MQnaHM86lv0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/MQnaHM86lv0',
                       'genre': 'Snaps'}, 
                     ],
            'SIMON’S CAT Black & White': [
                      {'name': 'SIMON’S CAT – FESTIVE FEAST (THANKSGIVING SPECIAL)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/UFZvaB2iKqc&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/UFZvaB2iKqc',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – KITTEN VS SNAKE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/OwTx_twzFRU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/OwTx_twzFRU',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – SPOOKED! (HALLOWEEN SPECIAL)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/rL8QC4L0-Rs&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/rL8QC4L0-Rs',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – SHOWDOWN (JAZZ TRILOGY! – 3/3)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/lPg9iBVOIZE&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/lPg9iBVOIZE',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – ON THE FENCE (JAZZ TRILOGY! – 2/3)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/FHPKktGooVI&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/FHPKktGooVI',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – BORDERLINE (JAZZ TRILOGY! – 1/3)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/x15WEDWufPs&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/x15WEDWufPs',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – THE SNIP',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/AMHWyS5GyeY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/AMHWyS5GyeY',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – ARMCHAIR FAN',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/y6GcCjCb_m0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/y6GcCjCb_m0',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – CROW',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/w9JrUVI_h4I&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/w9JrUVI_h4I',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – STRETCHED OUT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/feYykx3Fq-k&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/feYykx3Fq-k',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – OFF TO THE VET (FULL FILM IN B&W!)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/CyYYHLygi3s&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/CyYYHLygi3s',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – POLISHED PAWS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/FZCutVRTub4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/FZCutVRTub4',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – THE TREE (TRUE STORY)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/9qlF_9PNhJs&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/9qlF_9PNhJs',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – PURRTHDAY CAKE (A 10TH BIRTHDAY SPECIAL)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/faYA_upR_a0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/faYA_upR_a0',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – HEAD OVER HEELS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/rplCCSqWXIY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/rplCCSqWXIY',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – A CHRISTMAS YARN',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/R-OZ2Tmi9pw&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/R-OZ2Tmi9pw',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – FIREWORKS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/BWsRpT9LNcQ&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/BWsRpT9LNcQ',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – KITTEN CRAZY TIME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/BkIuZVGTkM0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/BkIuZVGTkM0',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – FAST FOOD (A THANKSGIVING SPECIAL)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/nkXGohB02V0&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/nkXGohB02V0',
                       'genre': 'Black & White'}, 
                      {'name': 'SIMON’S CAT – DIY',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/9PhM-zCmTFs&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/9PhM-zCmTFs',
                       'genre': 'Black & White'}, 
                      {'name': 'HAMBUSH',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/TUBK4qUGogw&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/TUBK4qUGogw',
                       'genre': 'Black & White'}, 
                      {'name': 'SPIDER CAT (HALLOWEEN SPECIAL)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/ruTB5jBGXsE&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/ruTB5jBGXsE',
                       'genre': 'Black & White'}, 
                      {'name': 'SCRATCH POST',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/sz-UQfw8Qeg&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/sz-UQfw8Qeg',
                       'genre': 'Black & White'}, 
                      {'name': 'BED HEAD',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/SNAZGy7JStQ&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/SNAZGy7JStQ',
                       'genre': 'Black & White'}, 
                      {'name': 'WAITING GAME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/TayIfVa0QPs&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/TayIfVa0QPs',
                       'genre': 'Black & White'}, 
                      {'name': 'COPY CAT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/IuHnAq6PMT4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/IuHnAq6PMT4',
                       'genre': 'Black & White'}, 
                      {'name': 'DINNER DATE: JUST DESSERTS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/iyvHcIEm5Sw&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/iyvHcIEm5Sw',
                       'genre': 'Black & White'}, 
                      {'name': 'HOP IT: EASTER EGGSTRAVAGANZA',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/WNOl71hB1es&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/WNOl71hB1es',
                       'genre': 'Black & White'}, 
                      {'name': 'DINNER DATE: MAIN COURSE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/xdP_R7gCUE4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/xdP_R7gCUE4',
                       'genre': 'Black & White'}, 
                      {'name': 'DINNER DATE: STARTERS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/Wy3a0wMgbD8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/Wy3a0wMgbD8',
                       'genre': 'Black & White'}, 
                      {'name': 'LITTLE BOX',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/tNhFAiFzgl8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/tNhFAiFzgl8',
                       'genre': 'Black & White'}, 
                      {'name': 'BED SHEETS!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/P3y8vc-3iVU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/P3y8vc-3iVU',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW HALLOWEEN FILM OUT! THE MONSTER!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/pTBjHjRhx_Y&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/pTBjHjRhx_Y',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW FILM OUT! TRASH CAT!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/yEvhDTWSRec&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/yEvhDTWSRec',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW FILM OUT! FISH TANK!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/R9qdyXCVNVk&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/R9qdyXCVNVk',
                       'genre': 'Black & White'}, 
                      {'name': 'WATCH SIMON’S CAT IN 360!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/8Q8EnGYh8f4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/8Q8EnGYh8f4',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW FILM OUT! LASER TOY!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/izbry0qk8LU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/izbry0qk8LU',
                       'genre': 'Black & White'}, 
                      {'name': 'PLAY LIKE A CAT – SIMON’S CAT & ELMO',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/XOCaWUEHPAo&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/XOCaWUEHPAo',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW FILM OUT! MUDDY PAWS!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/CLnHzv7OKao&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/CLnHzv7OKao',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW FILM OUT! FIELD TRIP!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/B7sggjEBnZg&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/B7sggjEBnZg',
                       'genre': 'Black & White'}, 
                      {'name': 'NEW FILM OUT! FAST TRACK',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/fV6O722O_ew&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/fV6O722O_ew',
                       'genre': 'Black & White'}, 
                      {'name': 'TOUGH LOVE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/4nd01DwuHwE&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/4nd01DwuHwE',
                       'genre': 'Black & White'}, 
                      {'name': 'CHRISTMAS COLLECTION',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/ZNfGVE-_rms&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/ZNfGVE-_rms',
                       'genre': 'Black & White'}, 
                      {'name': 'SNOW CAT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/oh_1c4NFnk4&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/oh_1c4NFnk4',
                       'genre': 'Black & White'}, 
                      {'name': 'PUG LIFE!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/fcoNym1Q1Ds&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/fcoNym1Q1Ds',
                       'genre': 'Black & White'}, 
                      {'name': 'BOX CLEVER',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/ZpCl5O6tTv8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/ZpCl5O6tTv8',
                       'genre': 'Black & White'}, 
                      {'name': 'PIZZA CAT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/OsOYg5gpS0s&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/OsOYg5gpS0s',
                       'genre': 'Black & White'}, 
                      {'name': 'WATCH OUR KITTEN COLLECTION COMPILATION!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/7oZu3-PU6KA&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/7oZu3-PU6KA',
                       'genre': 'Black & White'}, 
                      {'name': 'APRIL SHOWERS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/0kgTfbL21G8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/0kgTfbL21G8',
                       'genre': 'Black & White'}, 
                      {'name': 'BUTTERFLIES!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/TZPN9g2pmPQ&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/TZPN9g2pmPQ',
                       'genre': 'Black & White'}, 
                      {'name': 'CATNIP',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/UhQ9HquDNEM&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/UhQ9HquDNEM',
                       'genre': 'Black & White'}, 
                      {'name': 'WASHED UP',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/L8qOb8mdTTU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/L8qOb8mdTTU',
                       'genre': 'Black & White'}, 
                      {'name': 'SCAREDY CAT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/MGEzSJIFicY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/MGEzSJIFicY',
                       'genre': 'Black & White'}, 
                      {'name': 'HOT WATER',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/ApN73TUVMEU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/ApN73TUVMEU',
                       'genre': 'Black & White'}, 
                      {'name': 'PAWTRAIT',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/k1i9YmUgY0Q&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/k1i9YmUgY0Q',
                       'genre': 'Black & White'}, 
                      {'name': 'CRAZY TIME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/l5ODwR6FPRQ&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/l5ODwR6FPRQ',
                       'genre': 'Black & White'}, 
                      {'name': 'SMITTEN',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/aE_gN8fA2xE&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/aE_gN8fA2xE',
                       'genre': 'Black & White'}, 
                      {'name': 'CHRISTMAS PRESENCE (PART 1)',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/abPLDLV8O4s&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/abPLDLV8O4s',
                       'genre': 'Black & White'}, 
                      {'name': 'SCARY LEGS',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/19jaOSNibkU&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/19jaOSNibkU',
                       'genre': 'Black & White'}, 
                      {'name': 'SUITCASE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/_dm_2G-rIOs&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/_dm_2G-rIOs',
                       'genre': 'Black & White'}, 
                      {'name': 'FLOWER BED',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/kWuIGAZ1x2I&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/kWuIGAZ1x2I',
                       'genre': 'Black & White'}, 
                      {'name': 'SCREEN GRAB',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/LpHpm_b0vRY&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/LpHpm_b0vRY',
                       'genre': 'Black & White'}, 
                      {'name': 'FEED ME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/Te4wx4jtiEA&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/Te4wx4jtiEA',
                       'genre': 'Black & White'}, 
                      {'name': 'ICECAPADE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/Dzz6lUsF19g&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/Dzz6lUsF19g',
                       'genre': 'Black & White'}, 
                      {'name': 'NUT AGAIN',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/h4E-uiaIxNc&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/h4E-uiaIxNc',
                       'genre': 'Black & White'}, 
                      {'name': 'FETCH',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/FatA6Pyw_D8&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/FatA6Pyw_D8',
                       'genre': 'Black & White'}, 
                      {'name': 'SPRINGTIME',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/ITZiZcHfj8s&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/ITZiZcHfj8s',
                       'genre': 'Black & White'}, 
                      {'name': 'READY, STEADY, SLOW!',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/OQwD0QCbxaA&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/OQwD0QCbxaA',
                       'genre': 'Black & White'}, 
                      {'name': 'WINDOW PAIN',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/XrivBjlv6Mw&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/XrivBjlv6Mw',
                       'genre': 'Black & White'}, 
                      {'name': 'TONGUE TIED',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/4Z6YUGGlwtA&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/4Z6YUGGlwtA',
                       'genre': 'Black & White'}, 
                      {'name': 'SHELF LIFE',
                       'thumb': 'http://deny.g6.cz/yt/getimage.php?videoid=https://youtu.be/3PtFwlKfvHI&sz=hd',
                       'video': 'http://deny.g6.cz/yt/getvideo.php?videoid=https://youtu.be/3PtFwlKfvHI',
                       'genre': 'Black & White'}, 
                     ]}



def get_url(**kwargs):
    return '{0}?{1}'.format(_url, urlencode(kwargs))


def get_categories():
    return VIDEOS.iterkeys()


def get_videos(category):
    return VIDEOS[category]


def list_categories():
    xbmcplugin.setPluginCategory(_handle, 'My Video Collection')
    xbmcplugin.setContent(_handle, 'videos')
    categories = get_categories()
    for category in categories:
        list_item = xbmcgui.ListItem(label=category)
        list_item.setArt({'thumb': VIDEOS[category][0]['thumb'],
                          'icon': VIDEOS[category][0]['thumb'],
                          'fanart': VIDEOS[category][0]['thumb']})
        list_item.setInfo('video', {'title': category,
                                    'genre': category,
                                    'mediatype': 'video'})
        url = get_url(action='listing', category=category)
        is_folder = True
        xbmcplugin.addDirectoryItem(_handle, url, list_item, is_folder)
    xbmcplugin.addSortMethod(_handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
    xbmcplugin.endOfDirectory(_handle)


def list_videos(category):
    xbmcplugin.setPluginCategory(_handle, category)
    xbmcplugin.setContent(_handle, 'videos')
    videos = get_videos(category)
    for video in videos:
        list_item = xbmcgui.ListItem(label=video['name'])
        list_item.setInfo('video', {'title': video['name'],
                                    'genre': video['genre'],
                                    'mediatype': 'video'})
        list_item.setArt({'thumb': video['thumb'], 'icon': video['thumb'], 'fanart': video['thumb']})
        list_item.setProperty('IsPlayable', 'true')
        url = get_url(action='play', video=video['video'])
        is_folder = False
        xbmcplugin.addDirectoryItem(_handle, url, list_item, is_folder)
    xbmcplugin.addSortMethod(_handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
    xbmcplugin.endOfDirectory(_handle)


def play_video(path):
    play_item = xbmcgui.ListItem(path=path)
    xbmcplugin.setResolvedUrl(_handle, True, listitem=play_item)


def router(paramstring):
    params = dict(parse_qsl(paramstring))
    if params:
        if params['action'] == 'listing':
            list_videos(params['category'])
        elif params['action'] == 'play':
            play_video(params['video'])
        else:
            raise ValueError('Invalid paramstring: {0}!'.format(paramstring))
    else:
        list_categories()


if __name__ == '__main__':
    router(sys.argv[2][1:])
